FROM alpine:latest

RUN apk add --no-cache curl unzip

RUN curl -o /tmp/ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip && \
    unzip /tmp/ngrok.zip -d /usr/local/bin && \
    rm /tmp/ngrok.zip && \
    chmod +x /usr/local/bin/ngrok

COPY ngrok.sh /ngrok.sh
RUN chmod +x /ngrok.sh

WORKDIR /app